# Generated by Django 4.1.3 on 2022-11-13 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddIndex(
                    model_name='question',
                    index=models.Index(fields=['-pub_date'], name='polls_quest_pub_dat_ca81de_idx'),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql='CREATE INDEX CONCURRENTLY polls_quest_pub_dat_ca81de_idx ON polls_question(pub_date DESC)',
                    reverse_sql='DROP INDEX polls_quest_pub_dat_ca81de_idx',
                )
            ]
        ),
    ]
