# Generated by Django 4.1.3 on 2022-11-13 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['-pub_date'], name='polls_quest_pub_dat_ca81de_idx'),
        ),
    ]
